### ISSUE TITLE
No channels available

### ISSUE THREAD

**Issue by PoGibas** [ealeksandrov/SomaFM-miniplayer#1]
After opening app and trying to select station `Stations` - list is empty `No channels available`

---

Version 1.1.0

**Comment by ealeksandrov** [comment]
Thanks for reporting.

Spotted a bug, can you try this build with a fix?
[SomaFM-miniplayer.app.zip](https://github.com/ealeksandrov/SomaFM-miniplayer/files/2073902/SomaFM-miniplayer.app.zip)

**Comment by PoGibas** [comment]
Given version fixed bug

**Comment by ealeksandrov** [comment]
Fixed in becb874c2f55bc684428f5be8de14c26f5a0a281.
Released in [1.2.0](https://github.com/ealeksandrov/SomaFM-miniplayer/releases/tag/1.2.0).
