### ISSUE TITLE
Where to donate?

### ISSUE THREAD

**Issue by staticwave** [ealeksandrov/SomaFM-miniplayer#3]
Love this, thanks. I use it every day. I'd be happy to send you a small donation if you let me know the best way.

**Comment by ealeksandrov** [comment]
Glad you liked it!
If you wish, please support SomaFM directly - https://somafm.com/support/

**Comment by staticwave** [comment]
Definitely, I've been a monthly supporter of SomaFM for years. I just wanted to support your project since I use it all the time.

**Comment by ealeksandrov** [comment]
Thanks for that, but this project doesn't require much of continuous support and I did it for myself first :)
Happy to hear that it fits you well 🎉

**Comment by staticwave** [comment]
Ok, well thanks again for sharing it.
